language: android
install:
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export DEPOT_TOOLS_HOME=$(pwd)/depot_tools
  - export PATH=$(pwd):$DEPOT_TOOLS_HOME:$PATH
script:
  - alias git=mygit
  - chmod +x android-make.sh
  - ./android-make.sh 
branches:
  only:
    - master  
    
